# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol_post', models.CharField(max_length=100, verbose_name='titol de la noticia')),
                ('text_post', models.TextField(verbose_name='Contingut de la noticia')),
                ('creacio_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titol_post'],
            },
        ),
    ]
