# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='centre',
            fields=[
                ('id_centre', models.AutoField(primary_key=True, serialize=False)),
                ('cit_centre', models.CharField(max_length=20)),
                ('cp_centre', models.CharField(max_length=5)),
                ('mail_centre', models.EmailField(max_length=80)),
                ('cod_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='empresa.empresa')),
            ],
        ),
    ]
